# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-21 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'app', '0001_squashed_0004_example_original_dir'), (b'app', '0002_example_main'), (b'app', '0003_book'), (b'app', '0004_book_author'), (b'app', '0005_delete_book'), (b'app', '0006_programrun')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basename', models.TextField()),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToolOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('output', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='resources',
            field=models.ManyToManyField(to=b'app.Resource'),
        ),
        migrations.AddField(
            model_name='example',
            name='original_dir',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example',
            name='main',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProgramRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_dir', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
