# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
