# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
